name: CI Pipeline

# Trigger the workflow on push or pull request to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build the backend with Maven
    - name: Build Backend
      working-directory: Backend/SFANT/SFANT
      run: mvn clean package -DskipTests

    # Step 4 (optional): Archive the jar for future use
    - name: Archive Backend Jar
      uses: actions/upload-artifact@v3
      with:
        name: backend-jar
        path: Backend/SFANT/SFANT/target/*.jar
