name: CI Pipeline

# Run this workflow when code is pushed or a pull request is made to main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Get code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build Backend with Maven
      - name: Build Backend
        working-directory: Backend
        run: mvn clean package -DskipTests
